### ISSUE TITLE
Go Into NetworkMode (ps2)

### ISSUE THREAD

**Issue by inada-s** [inada-s/gdxsv#1]
Probably this is the most difficult phase of creating GDX server.

There is a talk of making a Dreamcast version of the game server, but there are a lot of debug symbols left in the PS2 version of the game, so I plan to develop a server based on the PS2 version.

I believe the Dreamcast and PS2 versions to be served on almost the same game server.

**Comment by gh0stl1ne** [comment]
This means Gundam DX (PS2) is a modem-only game?

I never tried to modify a game to use the broadband adapter instead of the modem. Interesting task!

Online revival will be easy, it's plain KDDI:
```C
void Send_LineCheck(void)

{
  SetSendCommand((message *)&send_work,0x6001);
  SetSendCategory((message *)&send_work,2);
  SetSendCommandLen((message *)&send_work);
  Write_Socket((message *)&send_work);
  return;
}
```

**Comment by inada-s** [comment]
> This means Gundam DX (PS2) is a modem-only game?

YES. When the game released, only Multi-Matching (Not Multi Matching BB) is on service.

> I never tried to modify a game to use the broadband adapter instead of the modem.

This task is the first step. I'm going to modify pcsx2 codes so that it can enter online mode to get started with server development.

**Comment by inada-s** [comment]
### replace modem_recognition button into network_battle button
```
cpu->write32(0x003c4f58, 0x0015f110);
```

### skip ppp step
```
cpu->write32(0x0035a660, 0x24030002);
```

dns lookup phase have something tricky..

**Comment by inada-s** [comment]
### Note: Ave_XXX functions
`Ave_SifCallRpc` is a function to communicate AVE_TCP library.
other Ave_XXX functions are wrapper of `Ave_SifCallRpc`.

https://www.retroreversing.com/playStation-2-architecture#example-of-sif-in-action

> An example of using the SIF to communicate between both processors is the controller pad libraries. We want to communicate between libpad.a which runs on the Emotion Engine and padman.irx which runs on the I/O Processor. So during the VBlank period the IOP Padman.irx uses SIFDMA to send controller information (such as which buttons are pressed) to the Emotion Engine. The Emotion Engine can then request this information by calling the API scePadRead


If needed to modify the game to make good use of Ethernet adapter,
1. investigate how AVE_TCP functions are used in MonsterHunter and impl them as patches.
2. develop a new iop library using [ps2dev](https://github.com/ps2dev/ps2sdk/tree/master/iop/tcpip) to replace AVE_TCP library.

Either way, both seem to be difficult.

**Comment by inada-s** [comment]
hand-decompiled `TcpGetStatus`

```cpp
// 00381e70  TcpGetStatus

void TcpGetStatus() {
	// stack size = 0x0010
	sp[0] = s0
	sp[1] = ra

	s0 = a1
	// dsll32: Doubleword Shift Left Logical Plus 32
	a0 = a1 << (16+32)
	a2 = s0 + 2
	a3 = s0 + 4
	
	// dsra32		a0, a0, 16
	a0 = a0 >> (16+32)

	v0 = Ave_TcpStat(a0, a1, a2, a3) // Ave_TcpStat is `select(2)` like function
	
	v0 <<= 16+32
	v0 >>= 16+32
	
	if (0 <= v0) { // bgez 00381eac
		// lhu		v1, $0000(s0)		# 00381eac:96030000
		v1 = s0[0]
        // Set on Less Than Immediate Unsigned
		// sltiu		at, v1, $000b
		at = v1 < 11
		if (at == 0) { // beql: execute the delay slot only if the branch is taken.
			// Note: guess it is smaller than header length.
			v1 = 7
			s0[0] = v1
		} else {
			v1 >>= 2
			switch (v1 + a0) {
				case 0: s0[0]=0 break
				case 1: v1=1, s0[0]=v1 break
				case 2: v1=2, s0[0]=v1 break
				case 3: v1=3, s0[0]=v1 break
				case 4: v1=4, s0[0]=v1 break
				case 5: v1=5, s0[0]=v1 break
				case 6: v1=6, s0[0]=v1 break
				case 7: v1=7, s0[0]=v1 break
				case 8: v1=8, s0[0]=v1 break
				case 9: v1=9, s0[0]=v1 break
				case 10:v1=10,s0[0]=v1 break
			}
		}
	}
	ra = sp[1]
	s0 = sp[0]
}
```

**Comment by inada-s** [comment]
I modified the pcsx2 code to set breakpoints on functions likely to be involved in network, and to call C ++ callbacks when passing through those functions.
In the callbacks, skip the ppp process and bypass tcp's Open / Read / Write to winsock's.

**Comment by inada-s** [comment]
A little progress :)
![image](https://user-images.githubusercontent.com/1726079/77485342-3c94d200-6e70-11ea-8e56-a1544a47fa3b.png)

**Comment by inada-s** [comment]
next task is https://github.com/inada-s/gdxsv/issues/3

**Comment by gh0stl1ne** [comment]
You're super fast. I'm still in the process of getting the game. Not an easy task these days.
