### ISSUE TITLE
Play battlelog

### ISSUE THREAD

**Issue by inada-s** [inada-s/gdxsv#100]
Load the battlelog file and play offline.
I haven't decided how to use it in the end.

**Comment by vkedwardli** [comment]
The perfect way for spectators if we do it live

**Comment by vkedwardli** [comment]
`0x1BFBB0` 前回の戦いのリプレイデータを
`0x1BFBD0` ファイルにセーブしますか？

Just noticed these string during translation, battle replay data is an official function?

**Comment by inada-s** [comment]
which version? I did not know that.

**Comment by vkedwardli** [comment]
Found from DC2

**Comment by inada-s** [comment]
https://github.com/inada-s/flycast/pull/164
