### ISSUE TITLE
Support custom DNS server for dc ver

### ISSUE THREAD

**Issue by inada-s** [inada-s/gdxsv#13]
goal
---
- Prepare a DNS server for DC to connect to lobby server without editing original hostname in binary.
---

The flycast supports adding custom DNS server in the emu.cfg
We have to modify to use this.

https://github.com/inada-s/gdxsv/issues/6#issuecomment-610632543

**Comment by inada-s** [comment]
I added dns server impl.

and I added following setting in emu.cfg but it doesn't work..
```
[network]
DNS = 127.0.0.1
```

**Comment by inada-s** [comment]
this setting may overwrite default dreamcast live dns.
but I don't want to prepare generic dns server, so I think we should add secondary-dns option.

**Comment by inada-s** [comment]
The secondary DNS does not seem to be used when the primary DNS is working....

**Comment by vkedwardli** [comment]
Actually if there is one lobby server and players will be played thru the UDP Proxy (so no need the battle server), then the easiest way should be adding the A record to dreamcast live dns?

**Comment by inada-s** [comment]
It seems that cross play is not possible with real dream cast and emulator. ( not checked)
A mechanism for registering battle servers for each region is required.
This will be a big project....

**Comment by inada-s** [comment]
I plan to have one lobby server and one match server for each region.
Therefore, the setting of custom DNS is unnecessary.

**Comment by inada-s** [comment]
https://github.com/inada-s/gdxsv/issues/24

**Comment by AM2petterk** [comment]
Please try with Outtrigger to check compatibility between the SNAP system and the KDDI..
