### ISSUE TITLE
Widescreen Game Cheat

### ISSUE THREAD

**Issue by inada-s** [inada-s/gdxsv#138]
The current widescreen mode works pretty well, but sometimes objects are hidden at the edges of the screen.
Find the setting in the game and skip to show the edge of the screen.

**Comment by inada-s** [comment]
I found the following address on the PS2 version. I tried changing the values but it didn't affect the appearance.
![image](https://user-images.githubusercontent.com/1726079/123550497-b40a8d00-d7a8-11eb-9bbf-1cb0cbdd95de.png)

PCSX2 doesn't have an option to show the outside of the screen, so I'll have to try the same in the DC version.

**Comment by inada-s** [comment]
Found similar values in DC2 version.
![image](https://user-images.githubusercontent.com/1726079/123552468-4151df80-d7b1-11eb-822a-8c65f3ed9272.png)

Snippet to edit these values.
```
    u32 v_12000 = 0x463b8000;
    WriteMem32_nommu(0x0c1e7950, v_12000);
    WriteMem32_nommu(0x0c1e7990, v_12000);

    u32 v_5_887931E_39 = 0x1D28;
    WriteMem32_nommu(0x0c1e7944, v_5_887931E_39);
    WriteMem32_nommu(0x0c1e7954, v_5_887931E_39);
    WriteMem32_nommu(0x0c1e7964, v_5_887931E_39);
    WriteMem32_nommu(0x0c1e7974, v_5_887931E_39);
    WriteMem32_nommu(0x0c1e7984, v_5_887931E_39);

    u32 v_1_33333 = 0x3FAAAAAB;
    WriteMem32_nommu(0x0c1e7948, v_1_33333);
    WriteMem32_nommu(0x0c1e7958, v_1_33333);
    WriteMem32_nommu(0x0c1e7968, v_1_33333);
    WriteMem32_nommu(0x0c1e7978, v_1_33333);

    u32 v_1_0 = 0x3F800000;
    WriteMem32_nommu(0x0c1e7960, v_1_0);
    WriteMem32_nommu(0x0c1e7970, v_1_0);
    WriteMem32_nommu(0x0c1e7980, v_1_0);

    u32 v_0_01 = 0x3C23D70A;
    WriteMem32_nommu(0x0c1e795c, v_0_01);
    WriteMem32_nommu(0x0c1e796c, v_0_01);
    WriteMem32_nommu(0x0c1e797c, v_0_01);

    u32 v_1_01 = 0x3F8147AE;
    WriteMem32_nommu(0x0c1e794c, v_1_01);
    WriteMem32_nommu(0x0c1e798c, v_1_01);

    u32 v_0_5 = 0x3F000000;
    WriteMem32_nommu(0x0c1e7988, v_0_5);
```

**Comment by inada-s** [comment]
It seems that it is calculated with an aspect ratio of 4: 3.
4/3 = 1.33333

So float `3FAAAAAA` (`3FAAAAAB`) is key value.

**Comment by inada-s** [comment]
the value v_5_887931E_39 is like FOV? looks funny
![image](https://user-images.githubusercontent.com/1726079/123552841-123c6d80-d7b3-11eb-9e4a-f5536b37f39f.png)

**Comment by vkedwardli** [comment]
LOL, but could be useful for replay or VR headset

**Comment by inada-s** [comment]
In flycast's widescreen cheats, the aspect ratio has changed. Therefore, simply changing 1.3333 to 1.7777 works fine.
https://github.com/inada-s/flycast/blob/gdxsv-master/core/nullDC.cpp#L567-L568

**Comment by vkedwardli** [comment]
would be better if we don't hard code the value, I know someone who is using 21:9 monitor (2.3333333333)
emu.cfg or a new tab in the Settings?

**Comment by inada-s** [comment]
Widescreen cheats are achieved by stretching the results once the game has rendered.
Widescreen cheats for other games also rely on this.
If you stretch it to 21: 9, it will collapse.

I don't know what "Super Wide Screen" is, but let's go up to the level of Wide Screen.

**Comment by vkedwardli** [comment]
The new "Wide Screen" now is hard coded to 16:9
Super Wide Screen is the original Wide Screen with no limitation

**Comment by inada-s** [comment]
OMG :(
![image](https://user-images.githubusercontent.com/1726079/123556242-06f23d80-d7c5-11eb-8f45-796add304d11.png)

**Comment by vkedwardli** [comment]
Seems the MS is still clipped (happens right at the edge of the 16:9)

**Comment by vkedwardli** [comment]
If we don't apply value for `0x1E7948`, seems to be working:

![image](https://user-images.githubusercontent.com/602245/123556884-49fde200-d7c0-11eb-9eb4-53c153df5e75.png)

**Comment by vkedwardli** [comment]
whoops my bad, the value is fundamental to the wide screen hack LOL

**Comment by inada-s** [comment]
This value may also be used for 2D display on the lobby screen....

**Comment by vkedwardli** [comment]
`0x1E7958` is for the battle HUD
![image](https://user-images.githubusercontent.com/602245/123557165-f8eeed80-d7c1-11eb-8874-c2b44d5b076e.png)

**Comment by inada-s** [comment]
The value 3FAAAAAB found following addrs, but we have to modify used on 3D parts.
```
        0x0c1e7978,
        0x0c1e7968,
        0x0c1e7958,
        0x0c1e7948,
        0x0c2a0c80,
        0x0c2a0b2c,
        0x0c2a08e4,
        0x0c2a069c,
        0x0c2a0500,
        0x0c2a0234,
        0x0c2a0228,
        0x0c2a021c,
        0x0c2a0210,
        0x0c2a0204,
        0x0c29fae4,
        0x0c29fad8,
        0x0c29f004,
        0x0c29eff8,
        0x0c29ea84,
        0x0c29e1cc,
        0x0c29deb0,
        0x0c29dea4,
        0x0c29de98,
        0x0c29da04,
        0x0c29d9f8,
        0x0c29d9ec,
        0x0c29d374,
        0x0c29d368,
        0x0c29d35c,
        0x0c29c870,
        0x0c29c864,
```

**Comment by inada-s** [comment]
Perhaps hardcodes the coordinates without using 4/3 but some parts use 4/3 at the lobby scene. 👎

**Comment by vkedwardli** [comment]
Our could we just stretch the screen and apply memory patch only during `gdxsv.InGame()` ?

**Comment by inada-s** [comment]
It's not compatible with widescreen_cheat.
Even if that is good, it will change between offline and online mode, so we have to add some additional conditions.

**Comment by vkedwardli** [comment]
<img width="1673" alt="Screenshot 2021-06-28 at 2 53 35 AM" src="https://user-images.githubusercontent.com/602245/123558297-2048b900-d7c8-11eb-9cf7-077841de892a.png">
21:9 is working fine with the correct stretching

**Comment by inada-s** [comment]
What number of the Horizontal Streching value you use?
1.75 is the good value for 21:9 but cannot select it on flycast setting.

**Comment by vkedwardli** [comment]
Yes, was using 1.75 manually

**Comment by vkedwardli** [comment]
![Jun-29-2021 19-32-54](https://user-images.githubusercontent.com/602245/123790638-226a5f00-d911-11eb-938b-da9da0254639.gif)
![Jun-29-2021 19-34-34](https://user-images.githubusercontent.com/602245/123790652-26967c80-d911-11eb-9d4d-2bcd74a91311.gif)

Minor MS clipping on 16:9 ratio

**Comment by inada-s** [comment]
I think it is not so noticeable (my eyes got used to it).
Do you think it needs to be fixed?

**Comment by vkedwardli** [comment]
I will test with a little bit wider value like 17:9 to see if this can be solved easily

**Comment by inada-s** [comment]
Found a clipping function.. but not easy to handle.
`0c076bb0 PlayerTrans`  and `0x0c076c0e` is a key
![image](https://user-images.githubusercontent.com/1726079/123834573-85c0b500-d942-11eb-801c-24558a485852.png)

**Comment by vkedwardli** [comment]
The trick works (using 21:9 for easier comparison + demonstration)

![Jun-30-2021 01-21-10](https://user-images.githubusercontent.com/602245/123840858-7725ce00-d941-11eb-8f84-c6fa24400a5a.gif)

**Comment by inada-s** [comment]
What the trick? use larger number?

**Comment by vkedwardli** [comment]
Yes, just use a larger number for both screen stretching (`1.75`) and ratio (`0x40155555`)
When a 21:9 game is opened as fullscreen in a 16:9 monitor, Flycast will do a "Aspect Fill" so that it would just look the same as normal 16:9

**Comment by vkedwardli** [comment]
Actually it is possible to just stretch the screen when required, so that all other Game UI would look nicer

https://youtu.be/UaFtwqR8adg

**Comment by vkedwardli** [comment]
Turns out editing `gles.cpp` is not required, just `config::ScreenStretching.override` can do the trick

<img width="660" alt="Screenshot 2021-06-30 at 3 14 33 AM" src="https://user-images.githubusercontent.com/602245/123854510-62513680-d951-11eb-83b7-8407e61af7c4.png">

p.s. With Widescreen mode in Flycast, the output is cropped to 16:9, despite that I'm using 21:9 internally

**Comment by inada-s** [comment]
I pushed the 175 stretch. Let's take a look at.
https://github.com/inada-s/flycast/pull/41

**Comment by inada-s** [comment]
merged

**Comment by vkedwardli** [comment]
Tested, no out sync problem

and only a minor glitch:
<img width="1781" alt="Screenshot 2021-07-01 at 12 21 06 AM" src="https://user-images.githubusercontent.com/602245/124006858-5165fb00-da0d-11eb-98be-84bd5c1b2fdf.png">

**Comment by inada-s** [comment]
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=521738&highlight=Renpou+vs.+Zeon+DX#pid521738
PS2 (not MegaHits) ver cheat
```
gametitle=Kidou Senshi Gundam - Renpou vs. Zeon DX (J)(SLPM-65076)

//Widescreen hack 16:9

patch=1,EE,0013b808,word,3c024328 //3c024360
patch=1,EE,0019254c,word,3c024395 //3c024360
```

**Comment by vkedwardli** [comment]
the 21:9 value works for 16:9 is pure luck, extra stretching won't work for 21:9 monitor even if I stretch it 10 times wider
