### ISSUE TITLE
Rollback based network sync

### ISSUE THREAD

**Issue by inada-s** [inada-s/gdxsv#148]
Very difficult but worth a try.

**Comment by vkedwardli** [comment]
wow........

**Comment by inada-s** [comment]
FirstStep
https://youtu.be/SUB2wOAfHV4
I'm not sure this direction will work.

**Comment by inada-s** [comment]
There were a lot of problems such as out-sync, display glitch, synchronization at the end of the game, etc.
My motivation has dropped..

**Comment by inada-s** [comment]
https://github.com/inada-s/flycast/pull/88
First version released. I will open a separate issue for the rest of the work.
