### ISSUE TITLE
GCE Latency investigation

### ISSUE THREAD

**Issue by vkedwardli** [inada-s/gdxsv#156]
A Hong Kong player spent some time on pinging different GCP setup, here are the results:

![telegram-cloud-photo-size-5-6323424386933173440-y](https://user-images.githubusercontent.com/602245/126754037-491b1dce-a7a1-4a64-9a1a-04919771eb06.jpg)
gdxsv Hong Kong Battle Server
`min / avg / max / mdev = 2.839 / 4.251 / 6.757 / 0.458 ms`

The following are his allocated VMs:
all screenshots here:[ping screenshots.zip](https://github.com/inada-s/gdxsv/files/6867454/ping.screenshots.zip)

n2 standard-2 preemptibility=off premium line, asia-east2-a
`min / avg / max / mdev = 3.126 / 4.390 / 4.758 / 0.216 ms`

n2 standard-2 preemptibility=off, premium line, asia-east2-b
`min / avg / max / mdev = 2.308 / 3.931 / 4.997 / 0.230 ms`

n2 standard-2 preemptibility=off, premium line, asia-east2-c
`min / avg / max / mdev = 2.788 / 4.822 / 5.072 / 0.239 ms`

n2 standard-2 preemptibility=on, premium line, asia-east2-a
`min / avg / max / mdev = 3.317 / 4.399 / 4.757 / 0.178 ms`

N1 standard-1 preemptible=on premium line, asia-east2-b
`min / avg / max / mdev = 3.783 / 4.449 / 5.962 / 0.285 ms`

e2 medium preemptibility=on premium line, asia-east2-a
`min / avg / max / mdev = 4.625 / 5.301 / 7.252 / 0.345 ms`

e2 medium, preemptibility=on, premium line, asia-east2-a
`min / avg / max / mdev = 3.474 / 5.113 / 8.541 / 0.381 ms`

e2 standard-2 preemptibility=on premium line, asia-east2-a
`min / avg / max / mdev = 3.363 / 4.399 / 5.761 / 0.272 ms`

e2 standard-2, preemptibility=on, standard line, asia-east2-a
`min / avg / max / mdev = 4.032 / 5.268 / 6.180 / 0.303 ms`

e2 standard-2 preemptibility=on premium line, asia-east2-b
`min / avg / max / mdev = 3.761 / 4.348 / 4.740 / 0.149 ms`

**Comment by inada-s** [comment]
moved:
https://github.com/inada-s/gdxsv/wiki/NetworkNote
