### ISSUE TITLE
Optimize ranking calculation

### ISSUE THREAD

**Issue by inada-s** [inada-s/gdxsv#180]
As the number of battle records has increased, it will take longer to calculate.
I believe it can be speeded up by saving the calculated state in a table.

**Comment by vkedwardli** [comment]
Maybe it's also a time to review the ranking logic? Sorting by "total winning count" seems to be returning the Most Hardworking Players instead of their true skills.

so may be something like https://github.com/mafredri/go-trueskill ?

**Comment by inada-s** [comment]
https://github.com/inada-s/gdxsv/pull/240
