### ISSUE TITLE
Ping display optimization

### ISSUE THREAD

**Issue by inada-s** [inada-s/gdxsv#195]
Like new gundam game:

https://g-rwee.ggame.jp/system/line_display.php
![image](https://user-images.githubusercontent.com/1726079/193443934-7ff5fcd3-5319-4d24-9faf-5df71659d0b6.png)

**Comment by vkedwardli** [comment]
Would this require extra information shared between peers?

Currently "self" only have the latency value to 3 other peers, but not other peers' to other peers' latency value

**Comment by vkedwardli** [comment]
![telegram-cloud-photo-size-5-6181481846718706320-y](https://user-images.githubusercontent.com/602245/193468392-763a42c7-96a6-443a-8c8b-aad55ce71771.jpg)
Designed by zetaeddie

**Comment by inada-s** [comment]
Nice
