### ISSUE TITLE
Out sync during battle

### ISSUE THREAD

**Issue by vkedwardli** [inada-s/gdxsv#26]
Sometimes this would happen right after reborn, could be time difference for "when can player start moving after reborn", seems never happen during Battle Start.

Game didn't show Connection Issue or disconnect, from player perspective the opponent's movement becomes unreasonable.

Testing environment:
macOS (server + Flycast) + Windows, both using Wi-Fi, over internet

Will try to screencap both screen for further investigation

**Comment by inada-s** [comment]
Is it a cross-match between windows and mac?
Are the emulator versions exactly the same?
Floating point error may occur that depending on the type of CPU arch and the implementation of flycast (I dont know the detail).

Anyways I don't think it's a server-side issue.

**Comment by vkedwardli** [comment]
Yes it is a cross match, but only happens during reborn sometimes (hard to reproduce), binaries are built from the same git commit, just log here for reference first.

**Comment by vkedwardli** [comment]
Ok, tested 1 v 1 on Windows (by my friends), out sync also occur after reborn

Windows <-> Internet <-> my server <-> Internet <-> Windows

**Comment by inada-s** [comment]
I doubted floating point errors, and looked for codes depending on CPU types.
https://github.com/inada-s/flycast/commit/6fa22262ad6c391e30fa2a89a61a3645bbc17ede

please test it on v0.2.1.

**Comment by inada-s** [comment]
out-sync on x86_64 seems to be fixed.
