### ISSUE TITLE
Ping test in lobby

### ISSUE THREAD

**Issue by inada-s** [inada-s/gdxsv#48]

**Comment by vkedwardli** [comment]
Should we add a ping utility inside `oslib.h`, something like `int os_AverageLatencyFromURL(const std::string& url);` ?

While the URL can be passed from server side, after the latency is calculated, user will post the message as chat message.

Full ping URLs list: https://github.com/ImJasonH/gcping/blob/master/config.js

**Comment by inada-s** [comment]
I was thinking about the same thing.
I'm reluctant to use machines from other projects without permission. 🤔 
Why should add it to oslib.h?

**Comment by vkedwardli** [comment]
So we can different implementation for Windows, macOS and Linux, just like the fetch string function: https://github.com/inada-s/flycast/commit/74f0f4daf255b1e79726053892d03bc6a4e92a6c#diff-eaca4e47eaee8fe16a01e0e22ec85d701777bf64f4a406f659c65e406a6f02a1R11

**Comment by vkedwardli** [comment]
Feedback from users: They think the game is not enjoyable when wireless players are connected, so I provided the connection medium detection to distinguish wireless and wired players

**Comment by inada-s** [comment]
Let's use simply http request to mesure latency.

**Comment by inada-s** [comment]
https://github.com/inada-s/flycast/commit/00ae82910967490991adada26c17c4683a9623de
