### ISSUE TITLE
[Flycast] Porting Arcade Machines' characteristic to DC

### ISSUE THREAD

**Issue by vkedwardli** [inada-s/gdxsv#51]
I'm redirecting a popular request from HK players:

They would love all the "bugs" (or feature) to be ported back to the Dreamcast version.

e.g.
1. MSM-03 ゴッグ severe damage bug
2. Zaku angled dash + shooting machine gun -> cannot fly up by boost in the Dreamcast version

This is possible in the arcade:
![Oct-25-2020 16-54-37](https://user-images.githubusercontent.com/602245/97102725-d3fe2400-16e2-11eb-926a-ab4216f87aaf.gif)

**Comment by inada-s** [comment]
That's too hard.
It would be easier to play the arcade version.

If you know how to fix it, I agree with porting, but I don't want to investigate because it takes so long time.

**Comment by htc001120** [comment]
Actually, I guess the rom we're using fixed the issue
since I have another dreamcast emulator (Demul) with another rom which I was playing for more than 12 years ago
can perform those "features"
but the rom format doesn't compatible with Flycast so I cannot test it

**Comment by vkedwardli** [comment]
@htc001120  Please share the ROM name if you still have it? I thought only the NAOMI rom has these "features"

**Comment by htc001120** [comment]
@vkedwardli https://drive.google.com/file/d/0BzoPYmQRp_GnazNFc2pYd0V2Tms/view?usp=sharing
The rom and the old Demul is here
I have no windows machine on my hand now so cannot confirm if it is a Naomi rom, could anyone help to confirm it?
Many thanks

**Comment by inada-s** [comment]
Don't share rom. That's illegal.

**Comment by vkedwardli** [comment]
@htc001120 those are NAOMI arcade roms, and Flycast can run NAOMI roms with the correct security PIC

**Comment by inada-s** [comment]
I played the arcade version the other day. I realized that the appearance is similar to the DC version, but the behavior is quite different.

**Comment by inada-s** [comment]
Address book
![image](https://user-images.githubusercontent.com/1726079/123816585-6588fa00-d932-11eb-9a3d-abc772c84a05.png)

**Comment by inada-s** [comment]
like that?
PS2 ver patch: `002DF11C 00000000`
https://gyazo.com/d69fc3f322acfb912d6db36a5e408618

**Comment by inada-s** [comment]
I'm new to this technique, so take a look at how it behaves like AC version.

**Comment by inada-s** [comment]
Other MS also beams are also affected. This cannot be used... but good progress

**Comment by inada-s** [comment]
Note:
There are a little change in pl_shot_angle01
```
index dc2 ac
473 46 40
477 210 216
497 46 40
501 210 216
```
I dont know what is this

**Comment by vkedwardli** [comment]
I guess there are many subtle changes in all areas. E.g. Players reported that the attack range of `Gouf's dash heat sword` in dc2 is larger than ac

**Comment by inada-s** [comment]
It's impossible to make everything behave the same as AC.
I will investigate and fix only the parts that have a large impact on the battle because it takes several days for a verification.

> Players reported that the attack range of Gouf's dash heat sword in dc2 is much wider than ac (horizontal hitbox)
It would be helpful if you could show me how to reproduce and a video.

**Comment by inada-s** [comment]
The horizontal hitbox is not large. Please clarify how to reproduce.
https://github.com/inada-s/gdxsv/assets/1726079/e19046ae-aba7-4103-8a23-ebc35510995a

**Comment by vkedwardli** [comment]
could it be the "homing" (空格の誘導) is stronger in the AC version?
another floating point difference?

**Comment by inada-s** [comment]
I don't know.
As you can imagine, the research is very difficult.
I stopped investigating based on player impressions without evidence.
