### ISSUE TITLE
Ping limited lobby

### ISSUE THREAD

**Issue by inada-s** [inada-s/gdxsv#56]
Measure latency between player and for each gcp region, and prevent entry into fixed region lobbies.

**Comment by vkedwardli** [comment]
block >200ms may be a good start, so that HK people won't be able to join JP server (and vice versa)
no IP check is needed for fixed region

**Comment by htc001120** [comment]
is it possible to make it like kick only when the region has more than 4 or 8 players inside?

**Comment by vkedwardli** [comment]
@htc001120 I think that wouldn't be necessary since both JP & HK can enter Taiwan server?

**Comment by inada-s** [comment]
I think we need 50ms or less latency to play comfortably.
For the time being I set it to 64ms.
